-- MySQL Script generated by MySQL Workbench
-- 11/25/16 12:29:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dwsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dwsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dwsystem` DEFAULT CHARACTER SET utf8 ;
USE `dwsystem` ;

-- -----------------------------------------------------
-- Table `dwsystem`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsystem`.`Usuario` (
  `nombre_usuario` VARCHAR(25) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`nombre_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsystem`.`Carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsystem`.`Carga` (
  `NombreProyecto` VARCHAR(50) NOT NULL,
  `nombre_usuario` VARCHAR(25) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`NombreProyecto`, `Fecha`),
  INDEX `nombre_us_idx` (`nombre_usuario` ASC),
  CONSTRAINT `nombre_us`
    FOREIGN KEY (`nombre_usuario`)
    REFERENCES `dwsystem`.`Usuario` (`nombre_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwsystem`.`Genera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dwsystem`.`Genera` (
  `NombreVista` VARCHAR(50) NOT NULL,
  `nombre_usuario` VARCHAR(25) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`NombreVista`, `Fecha`),
  INDEX `nusuariog_idx` (`nombre_usuario` ASC),
  CONSTRAINT `nusuariog`
    FOREIGN KEY (`nombre_usuario`)
    REFERENCES `dwsystem`.`Usuario` (`nombre_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
